name: "Allo Allo"
author: "Schalk Neethling"
description: "A welcome bot GitHub action for your project"
inputs:
  issueGreeting: # id of input
    description: "The greeting to display to the new contributor"
    required: true
    default: "Welcome to the project! Thank you for your interest!"
outputs:
  newIssueComment: # output will be available to future steps
    description: "The issue comment"
runs:
  using: "node16"
  main: "dist/index.js"
